In [1]:
# Dependencies

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os

import time
import math

import preprocess

In [2]:
## Normal sEMG dataset
file_path = "./SEMG_DB1/N_TXT/"

input_array, output_array = preprocess.preprocess(file_path)
print(input_array.shape)
print(input_array)

/Users/hobinkang/Desktop/EMG _Leg_ Classification/preprocess.py:27: ConversionWarning: Some errors were detected !
    Line #7308 (got 1 columns instead of 5)
    Line #7309 (got 1 columns instead of 5)
    Line #7310 (got 1 columns instead of 5)
    Line #7311 (got 1 columns instead of 5)
    Line #7312 (got 1 columns instead of 5)
    Line #7313 (got 1 columns instead of 5)
    Line #7314 (got 1 columns instead of 5)
    Line #7315 (got 1 columns instead of 5)
    Line #7316 (got 1 columns instead of 5)
    Line #7317 (got 1 columns instead of 5)
    Line #7318 (got 1 columns instead of 5)
    Line #7319 (got 1 columns instead of 5)
    Line #7320 (got 1 columns instead of 5)
    Line #7321 (got 1 columns instead of 5)
    Line #7322 (got 1 columns instead of 5)
    Line #7323 (got 1 columns instead of 5)
    Line #7324 (got 1 columns instead of 5)
    Line #7325 (got 1 columns instead of 5)
    Line #7326 (got 1 columns instead of 5)
    Line #7327 (got 1 columns instead of 5)
  sel

(33, 36900, 5)
[[[-8.00e-04 -4.60e-03  3.00e-03 -9.80e-03 -5.91e+01]
  [ 7.00e-04 -5.30e-03  1.50e-03 -6.00e-03 -5.92e+01]
  [ 0.00e+00 -4.60e-03  3.00e-03 -1.50e-03 -5.93e+01]
  ...
  [ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
  [ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
  [ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]]

 [[-3.00e-03 -3.00e-03 -1.95e-02  4.50e-03 -5.26e+01]
  [-8.00e-04 -1.50e-03 -2.03e-02  5.20e-03 -5.26e+01]
  [-1.50e-03 -1.50e-03 -1.65e-02  3.70e-03 -5.26e+01]
  ...
  [ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
  [ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
  [ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]]

 [[-3.00e-03  7.00e-04 -8.00e-04  6.70e-03 -6.00e-01]
  [-1.50e-03  3.30e-02  7.00e-04  1.27e-02 -6.00e-01]
  [-8.00e-04  2.92e-02  0.00e+00  5.20e-03 -6.00e-01]
  ...
  [ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
  [ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
  [ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0

/Users/hobinkang/Desktop/EMG _Leg_ Classification/preprocess.py:27: ConversionWarning: Some errors were detected !
    Line #6930 (got 1 columns instead of 5)
    Line #6931 (got 1 columns instead of 5)
    Line #6932 (got 1 columns instead of 5)
    Line #6933 (got 1 columns instead of 5)
    Line #6934 (got 1 columns instead of 5)
    Line #6935 (got 1 columns instead of 5)
    Line #6936 (got 1 columns instead of 5)
    Line #6937 (got 1 columns instead of 5)
    Line #6938 (got 1 columns instead of 5)
    Line #6939 (got 1 columns instead of 5)
    Line #6940 (got 1 columns instead of 5)
    Line #6941 (got 1 columns instead of 5)
    Line #6942 (got 1 columns instead of 5)
    Line #6943 (got 1 columns instead of 5)
    Line #6944 (got 1 columns instead of 5)
    Line #6945 (got 1 columns instead of 5)
    Line #6946 (got 1 columns instead of 5)
    Line #6947 (got 1 columns instead of 5)
  self.array = np.genfromtxt(self.path, skip_header=7, invalid_raise=False)
/Users/hobinkang/

In [4]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

## One Hot Encode Prediction

print(output_array)
# convert output_array to one hot encoded classes
values = array(output_array)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

['mar', 'sen', 'pie', 'sen', 'pie', 'mar', 'pie', 'sen', 'pie', 'mar', 'pie', 'pie', 'pie', 'mar', 'sen', 'mar', 'pie', 'mar', 'sen', 'pie', 'sen', 'mar', 'sen', 'mar', 'pie', 'mar', 'sen', 'sen', 'sen', 'sen', 'mar', 'mar', 'pie']
['mar' 'sen' 'pie' 'sen' 'pie' 'mar' 'pie' 'sen' 'pie' 'mar' 'pie' 'pie'
 'pie' 'mar' 'sen' 'mar' 'pie' 'mar' 'sen' 'pie' 'sen' 'mar' 'sen' 'mar'
 'pie' 'mar' 'sen' 'sen' 'sen' 'sen' 'mar' 'mar' 'pie']
[0 2 1 2 1 0 1 2 1 0 1 1 1 0 2 0 1 0 2 1 2 0 2 0 1 0 2 2 2 2 0 0 1]
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [8]:
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.layers import Embedding
from keras.layers import LSTM

# Retrieve from input array shape
time_steps = input_array.shape[1]
n_features = input_array.shape[2]

# code for building an LSTM with 100 neurons and dropout.

model = Sequential()
model.add(LSTM(100, return_sequences=False, input_shape=(time_steps, n_features)))
model.add(Dropout(0.5))
#model.add(LSTM(100)) dramatically worse results
model.add(Dense(3, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [9]:
model.fit(input_array, onehot_encoded, batch_size=16, epochs=10)

Epoch 1/10
33/33 [==============================] - 84s 3s/step - loss: 0.7007 - acc: 0.6465
Epoch 2/10
33/33 [==============================] - 84s 3s/step - loss: 0.6804 - acc: 0.6667
Epoch 3/10
33/33 [==============================] - 82s 2s/step - loss: 0.6593 - acc: 0.6566
Epoch 4/10
33/33 [==============================] - 85s 3s/step - loss: 0.6468 - acc: 0.6768
Epoch 5/10
33/33 [==============================] - 84s 3s/step - loss: 0.6472 - acc: 0.6768
Epoch 6/10
33/33 [==============================] - 81s 2s/step - loss: 0.6341 - acc: 0.6667
Epoch 7/10
33/33 [==============================] - 80s 2s/step - loss: 0.6457 - acc: 0.6768
Epoch 8/10
33/33 [==============================] - 80s 2s/step - loss: 0.6234 - acc: 0.6768
Epoch 9/10
33/33 [==============================] - 80s 2s/step - loss: 0.6438 - acc: 0.6566
Epoch 10/10
33/33 [==============================] - 85s 3s/step - loss: 0.6504 - acc: 0.6667


In [10]:
## Abnormal sEMG dataset
abnormal_path = "./SEMG_DB1/A_TXT/"

abnormal_input_array, abnormal_output_array = preprocess.preprocess(file_path)

# convert output_array to one hot encoded classes
values = array(output_array)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
abnormal_onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(abnormal_onehot_encoded)

/Users/hobinkang/Desktop/EMG _Leg_ Classification/preprocess.py:27: ConversionWarning: Some errors were detected !
    Line #7308 (got 1 columns instead of 5)
    Line #7309 (got 1 columns instead of 5)
    Line #7310 (got 1 columns instead of 5)
    Line #7311 (got 1 columns instead of 5)
    Line #7312 (got 1 columns instead of 5)
    Line #7313 (got 1 columns instead of 5)
    Line #7314 (got 1 columns instead of 5)
    Line #7315 (got 1 columns instead of 5)
    Line #7316 (got 1 columns instead of 5)
    Line #7317 (got 1 columns instead of 5)
    Line #7318 (got 1 columns instead of 5)
    Line #7319 (got 1 columns instead of 5)
    Line #7320 (got 1 columns instead of 5)
    Line #7321 (got 1 columns instead of 5)
    Line #7322 (got 1 columns instead of 5)
    Line #7323 (got 1 columns instead of 5)
    Line #7324 (got 1 columns instead of 5)
    Line #7325 (got 1 columns instead of 5)
    Line #7326 (got 1 columns instead of 5)
    Line #7327 (got 1 columns instead of 5)
  sel

['mar' 'sen' 'pie' 'sen' 'pie' 'mar' 'pie' 'sen' 'pie' 'mar' 'pie' 'pie'
 'pie' 'mar' 'sen' 'mar' 'pie' 'mar' 'sen' 'pie' 'sen' 'mar' 'sen' 'mar'
 'pie' 'mar' 'sen' 'sen' 'sen' 'sen' 'mar' 'mar' 'pie']
[0 2 1 2 1 0 1 2 1 0 1 1 1 0 2 0 1 0 2 1 2 0 2 0 1 0 2 2 2 2 0 0 1]
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


/Users/hobinkang/Desktop/EMG _Leg_ Classification/preprocess.py:27: ConversionWarning: Some errors were detected !
    Line #6930 (got 1 columns instead of 5)
    Line #6931 (got 1 columns instead of 5)
    Line #6932 (got 1 columns instead of 5)
    Line #6933 (got 1 columns instead of 5)
    Line #6934 (got 1 columns instead of 5)
    Line #6935 (got 1 columns instead of 5)
    Line #6936 (got 1 columns instead of 5)
    Line #6937 (got 1 columns instead of 5)
    Line #6938 (got 1 columns instead of 5)
    Line #6939 (got 1 columns instead of 5)
    Line #6940 (got 1 columns instead of 5)
    Line #6941 (got 1 columns instead of 5)
    Line #6942 (got 1 columns instead of 5)
    Line #6943 (got 1 columns instead of 5)
    Line #6944 (got 1 columns instead of 5)
    Line #6945 (got 1 columns instead of 5)
    Line #6946 (got 1 columns instead of 5)
    Line #6947 (got 1 columns instead of 5)
  self.array = np.genfromtxt(self.path, skip_header=7, invalid_raise=False)
/Users/hobinkang/

In [11]:
# test on abnormal dataset

score = model.evaluate(abnormal_input_array, abnormal_onehot_encoded, batch_size=16)

33/33 [==============================] - 13s 379ms/step


In [12]:
score

[0.6438265081607935, 0.6767676870028178]